[input]
base_directory = "test/3b1b"
url_prefix = "https://www.youtube.com/watch?v="

[[input.files]]
path = "ch1.srt"
url = "WUvTyaaNkzM"
title = "The Essence of Calculus, Chapter 1"

[[input.files]]
path = "ch2.srt"
url = "9vKqVkMQHKk"
title = "The paradox of the derivative [2]"

[[input.files]]
path = "ch3.srt"
url = "S0_qX4VJhMQ"
title = "Derivative formulas through geometry [3]"

[[input.files]]
path = "ch4.srt"
url = "YG15m2VwSjA"
title = "Visualizing the chain rule and product rule [4]"

[output]
filename = "test/3b1b-debug.st"
debug = true
