# The smallest possible Federalist index
[input]
base_directory = "test/federalist"
files = [
    { path = "federalist-1.txt", url = "https://www.congress.gov/resources/display/content/The+Federalist+Papers#TheFederalistPapers-1", title = "Introduction" },
]

[output]
filename = "src/test-indexes/federalist-min.st"
debug = false
