[package]
name = "stork-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["v3"]
v2 = ["stork-lib/read-v2"]
v3 = ["stork-lib/read-v3"]

[dependencies]
console_error_panic_hook = "0.1.6"
once_cell = "1.8.0"
serde = "1.0.130"
serde_json = "1.0.68"
wasm-bindgen = "0.2.78"
stork-boundary = { path = "../stork-boundary" }
stork-lib = { path = "../stork-lib", default-features = false }
bytes = "1.1.0"
thiserror = "1.0.29"

# wasm-opt is out of date in wasm-bindgen, so we have to manually
# enable the "mutable globals" feature so wasm-opt doesn't reject
# the wasm blob that gets generated.
# See: https://github.com/rustwasm/wasm-pack/issues/886#issuecomment-667669802
# [package.metadata.wasm-pack.profile.release]
# wasm-opt = ["-Oz", "--enable-mutable-globals"]

[target.web]
wasm-opt = false